kind: Deployment
apiVersion: apps/v1
metadata:
  name: ado-agent-dev
  namespace: ado-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ado-dev
      env: dev
  template:
    metadata:
      labels:
        app: ado-dev
        env: dev
    spec:
      imagePullSecrets: 
        - name: "<Enter repo credentials>"
      containers:
        - name: ado-agent
          image: ubuntu-ado-agent:latest
          resources: {}
          env:
            - name: AZP_URL
              value: $AZP_URL
            - name: AZP_TOKEN
              value: $AZP_TOKEN
            - name: AZP_POOL
              value: $AZP_POOL
             - name: AZP_AGENT_NAME
              value: $AZP_AGENT_NAME            
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
